### ISSUE TITLE
Team Call #1 - Jul 1 2021 @ 1900 EST

### ISSUE THREAD

**Issue by gpthio** [MADS-Capstone-BLS-Job-Descriptions/predicting_demographics#1]
**Summary**

- Discussed project deadlines: Standups on Jul 6 (GT), Jul 20 (SN), Aug 3 (AF), Aug 17 (GT); Project submission on Aug 23
- GT created GitHub organization and [repo](https://github.com/MADS-Capstone-BLS-Job-Descriptions/predicting_demographics), invited AF and SN as organizers; discussed use of [GitHub Desktop](https://desktop.github.com/) as an option/personal preference
- Reviewed project goal: To be able to predict the demographic population distribution for a given occupation based on its numeric data and textual job descriptions  
- Agreed to individually dig deeper into the BLS data to get as many potentially useful features as possible such as age and prior years (e.g. have demographic profiles changed over time?):  [Labor Force Statistics from the Current Population Survey](https://www.bls.gov/cps/tables.htm)
- Looked at the [BLS API](https://www.bls.gov/bls/api_features.htm) and seems only possible to use it for obtaining numeric data (TBC); if not, will have to scrape data from the web pages
- Agreed to consult with professor and TAs about web scraping and text models; should be akin to text modeling with job descriptions (JDs) as topics to predict demographic composition 
- Looked at several occupations in the [Occupational Outlook Handbook (OOH)](https://www.bls.gov/ooh/) to check consistency of data structure and found some differences e.g. Comparing [High School Teachers](https://www.bls.gov/ooh/education-training-and-library/high-school-teachers.htm#:~:text=Plan%20lessons%20and%20instruct%20their%20students%20in%20the%20subject%20they%20teach&text=Grade%20students'%20assignments%20and%20exams,and%20to%20improve%20their%20abilities) and [Cooks](https://www.bls.gov/ooh/food-preparation-and-serving/cooks.htm), the latter has a reference link [See How to Become One](https://www.bls.gov/ooh/food-preparation-and-serving/cooks.htm#tab-4) next to “Typical Entry-Level Education
- Need to decide how to deal with these discrepancies which could be entered manually if found in only a small number of occupations, create a new description (e.g. “mixed”), or be imputed
- Looked at Amazon, but no Kindle version of OOH so can’t scan the data
- Initially, plan to get data from the following 5 tabs in the OOH:  - Summary (Median Pay, Number of Jobs, Job Outlook) - What They Do - Work Environment - How to Become One - Job Outlook (different vs Summary)
- Discussed possibly using JD photo descriptions as another feature (e.g. are these demographically biased?)
- AF mentioned neural network may be effective given the mixed numeric and text data, agreed to consult professor and TAs
- Discussed age as a possibly useful feature which could explain why some occupations are much more demographically diverse than others -- e.g. Computer scientists (younger) vs Factory Workers (older)
- Set next meeting at 0900 EDT on Jul 6  

**Tasks**

- [ ] ALL: Review use of GitHub as we will use the repo to manage the project
- [ ] ALL: Review BLS data and discuss findings at next meeting 
- [ ] GT: To record Jul 6 standup (see Summary notes for subsequent standup responsibilities)
- [ ] GT: Will attempt to contact BLS to confirm if text data can be obtained using the API
