### ISSUE TITLE
Team Call #2 - Jul 6 2021 @ 0900 EDT

### ISSUE THREAD

**Issue by gpthio** [MADS-Capstone-BLS-Job-Descriptions/predicting_demographics#2]
**Attendees**
- SN, GT 
- AH had work commitment, will follow-up on Slack

**Summary**
- SN found XML file containing all the data from the BLS occupational Outlook Handbook (OOH) covering 325 occupations: [](https://www.bls.gov/ooh/xml-compilation.xml)
- Decided we do not need to include [Data for Occupations Not Covered in Detail](https://www.bls.gov/ooh/about/data-for-occupations-not-covered-in-detail.htm#Architecture%20and%20engineering%20occupations) as we have sufficient data from the OOH and it has different data content and structure
- Discussed need to add folders to the repo (e.g. data, img, src). SN to add data folder and upload XML files, GT will add img folder and upload images from each BLS job description
<img width="924" alt="bls_sample_job_images" src="https://user-images.githubusercontent.com/75413805/124618258-a195f080-de45-11eb-9f13-cae4193b3ea3.png">
- Discussed using unsupervised learning to cluster jobs and 
- Discussed and addressed questions from Jake Huang and Winston Featherly-Bean:

Questions from Jake Huang:
_Interesting idea! I have a question regarding the "workforce" that is mentioned in the prompt: will this be geographically concentrated (i.e. all the workers in a certain state/province)?   > NO  Also, there are jobs where the male-female ratios are skewed (i.e. construction, engineering, etc.). How will this be taken into account? Happy to talk this over if you guys want to. Best of luck!_  

Answer:
Project will use national data. Demographic skew is central to the project as the demographic composition of each of the 325 jobs in the OOH are the targets which will be obtained from the   Labor Force Statistics from the Current Population Survey](https://www.bls.gov/cps/tables.htm)(LFS)

Questions from Winston Featherly-Bean:
_Great topic, looking forward to watching this project develop! I notice a couple initial ambiguities: will you use geographically specific jobs data, rather than national? (If so, why?) What precisely will be your target variable? You will find it very helpful to formalize your intended model(s) upfront: what are the features + target, what algorithm or structural form will you use for modelling, and why? (Please let me know if you'd like to think through possibilities together!)_

Answer:
Project will use national data. Target will be the age, race and sex composition of each job as noted above. We will determine exact target variables but could be mean age, racial composition (e.g. White, Black, Hispanic, Asian, Other) and male/female ratio. Features will be the numeric and text data taken from the OOH XML file and we are also considering using the images provided by the BLS for each of the 325 occupations which GT will label and upload. Since we will be using text, numeric and possibly image data, as noted last meeting, a neural network may be the most appropriate choice of model. Can also se GridSearch CV in a pipeline with different models to determine the optimal model and model parameters. Will consult teaching staff.

**References**
[Working with multiple types of Data in a single problem in Machine learning](https://towardsdatascience.com/working-with-multiple-types-of-data-in-a-single-problem-in-machine-learning-31b667930179)

**Tasks**

- [ ] SN: Create data folder in repo and add raw and cleaned XML files
- [ ] GT: Create img folder in repo
- [ ] GT: Finish downloading reference images from job descriptions and add to img folder
- [ ] AH: Review notes and provide follow-up comments as needed ahead of standup #1 submission today by 23:59 EDT  
- [ ] ALL: Provide standup comments for at least one other group today by 23:59 EDT
