### ISSUE TITLE
Team Call #4 - Jul 24 2021 @ 1000 EDT

### ISSUE THREAD

**Issue by gpthio** [MADS-Capstone-BLS-Job-Descriptions/predicting_demographics#7]
**Attendees**
- AF, SN, GT  

**Summary**
- Reviewed activities since last call: Reviewing Keras, CNN, RNN to determine appropriate data transformations and model implementation; uploaded flat file of OOH data; trained and ran image captioning model on OOH job description images; uploaded image data, image captioning results, and image captioning model
- Discussed data still to be processed and uploaded to GitHub: (1) Data for Occupations Not Covered in Detail (2)  (DONCD) dataset (2) Current Population Survey (CPS) 
- Per Issue #2 , the CPS data will be a vector with 13 levels: **Sex**: 1 level (% of women); **Age**: 7 levels (age buckets); **Race**: 5 levels (Black, Hispanic/Latino, White, Asian, Other). These will add up to > 100% due to Hispanic/Latino not being a racial category so they can and do identify as Black or White for example
- Reviewed project deliverables: (1) Standups (2) GitHub repo (3) Blog
- Agreed to produce a presentation as the final product around which blog will be  produced including video discussion
- Presentation elements: (1) Model structure, specification rationale and train/test/validate (2) Sample images, job descriptions and numerical data (3) If possible, present results using LIME to interpret results and explain most important model factors (4) Next steps and follow-on projects
- Reviewed image captions and discussed use and differences between captioning vs object detection models
- Agreed to proceed with current image captions to be used as inputs to main NN model together with text job descriptions and numerical data
- AF to complete review of NLP reference book by next call and make recommendation for appropriate text data representation for use in NN (e.g. vectorized vs non-vectorized, ordered vs BOW/TF-IDF)
- Given limited scope and size of BLS dataset, clarified purpose of project is a proof of concept that there is a correlation between the demographic composition of a job and its description as represented by text, images and numeric data 
- Example of a possible follow-on project requiring greater quantity and diversity of data (e.g  job postings and applicant demographic data) is a model that can take basic job requirements as inputs and generate job descriptions that will maximize the diversity of job applicants
- For this project a useful outcome would be the ability to identify common attributes of jobs (e.g. public-facing) that are less diverse that could alert employers to be more careful in creating these job descriptions
- Next call set for Mon Jul 26 @ 1800 EDT

** Reference links**
CPS data to vectorize
[](https://www.bls.gov/cps/cpsaat11.xlsx)
[](https://www.bls.gov/cps/cpsaat03.xlsx)

**Tasks**
- [ ] AF: Complete background reading on NLP to determine best data text data representation
- [ ] AF: Upload Data for Occupations Not Covered in Detail 
- [ ] SN: Process and upload CPS data to create vector of demographic levels as described above
- [ ] GT: Follow-up reading on object detection vs image captioning
