### ISSUE TITLE
Team Call #4 - Jul 26 2021 @ 1800 EDT

### ISSUE THREAD

**Issue by gpthio** [MADS-Capstone-BLS-Job-Descriptions/predicting_demographics#8]
**Attendees**
- AF, SN, GT  

**Summary**
- Found URLs to images under job description tabs in XML file and agreed to use those in `What They Do`, `Work Environment`, `How to Become One` together with thumbnails for each job shown in the table at the job category level (see examples below)

What They Do
<img width="798" alt="sample_what_they_do" src="https://user-images.githubusercontent.com/75413805/127071984-673ee84a-6ecd-4f0c-a88f-de4f09e13fc3.png">

Thumbnails
<img width="611" alt="sample_thumbnails" src="https://user-images.githubusercontent.com/75413805/127072395-c8cd3cc0-4ac6-44ba-8c2d-da3098bd6596.png">

- Decided to use object detection vs captioning model for images since objects (nouns) rather than actions (verbs) are associated with demographics (gender, age, race) 
- Will pass each image to an object detection NN to generate a word vector for each image, then combine all words into a dictionary for all jobs represented as a 297 x n sparse matrix of n words with each column value representing the word count.
- Perform train and test to determine optimal NN structure then use final layer before prediction as input to be concatenated with text description and numerical data in final model
- Initial discussion on possible visualizations: (1) Show several example job descriptions with their name, images, description, numeric data, predicted vs actual demographic levels (2) 13x13 scatter plot matrix to show correlations between demographic levels (could be faceted by occupation group, see example below)

<img width="645" alt="seaborn_scatterplot_matrix" src="https://user-images.githubusercontent.com/75413805/127074882-8d17fa03-b028-446e-b644-86c62c8b6289.png">
 
**Reference links**
[Keras: Multiple Inputs and Mixed Data](https://www.pyimagesearch.com/2019/02/04/keras-multiple-inputs-and-mixed-data/)

**Tasks**
- [ ] SN: Use regex to get URLs of the four desired images from the OOH job description (ideally as separate file with job name and category -- i.e. 297 x 6 table
- [ ] SN: Process and upload CPS age data with correct link provided by AF:  https://www.bls.gov/cps/cpsaat11b.htm
- [ ] AF, GT: Research concatenating different data types 
- [ ] GT: Find best object detection model and run on thumbnail images (e.g. Yolo)
- [ ] ALL: Review Keras reference above
